version: '3.1'

services:

  attic-search:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_USER=dev
      - MONGODB_PASS=test

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
